site_name: Documentation - Bachelor Project 2024
site_description: Documentation for Bachelorgruppe-0
site_author: Bachelorgruppe-0
copyright: Copyright 2024 Bachelorgruppe-0 - Creative Commons Attribution Non Commercial

#site_url: https://localhost:8000/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/eye
        name: Switch to system preference
  font:
    text: Roboto
    code: Ubuntu Mono
  #logo: images/routine_FILL1_wght700_GRAD200_opsz48.svg
  #favicon: images/routine_FILL1_wght700_GRAD200_opsz48.svg
  nav_style: dark
  features:
    - navigation.sections
    - content.code.annotate
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: index.md
  - Original Website: 
      - Design: original_website_design.md
      - Frameworks: original_website_frameworks.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: JennyHov/Bachelor_prosjekt
      branch: main 

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.keys
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/JennyHov/Bachelor_prosjekt.git
repo_name: Bachelor_prosjekt.git
edit_uri: edit/main/docs/